inherit_gem:
  rubocop-github:
    - config/default.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

RequireParentheses:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'ext/tree-sitter/tree-sitter/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'
